apiVersion: v1
kind: Template
metadata:
  name: vulnerability-ui
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: vulnerability
    spec:
      envName: ${ENV_NAME}
      title: Vulnerability
      deploymentRepo: https://github.com/RedHatInsights/vulnerability-ui
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/vulnerability
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - appId: "vulnerability"
          title: "Vulnerability"
          href: "/insights/vulnerability"
          product: "Red Hat Insights"
          expandable: true
          routes:
            - appId: 'vulnerability'
              title: 'CVEs'
              href: '/insights/vulnerability/cves'
            - appId: 'vulnerability'
              title: 'Systems'
              href: '/insights/vulnerability/systems'
            - appId: 'vulnerability'
              title: 'Reports'
              href: '/insights/vulnerability/reports'
      module:
        manifestLocation: "/apps/vulnerability/fed-mods.json"
        modules:
          - id: "vulnerability"
            module: "./RootApp"
            routes:
              - pathname: /insights/vulnerability

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/insights-management-tenant/insights-vulnerability/vulnerability-ui
